"""Mermaid emitter — a projection of the Canonical Knowledge Model."""
import re

from ...runtime.phases import feature


def _nid(i):
    return re.sub(r"[^A-Za-z0-9_]", "_", i)


@feature("graph projection",
         input_phase="ckm", output_phase="projection",
         invariants=["one node per model node, one edge per model edge",
                     "families are visually distinguished"],
         determinism="a pure function of the canonical model")
def emit(ckm):
    s = ckm["statistics"]
    L = ["# Generated graph\n",
         "> **A projection of the Canonical Knowledge Model.**",
         "> Generated by the compiler. Do not edit.\n",
         f"\n**{s['nodes']} nodes, {s['edges']} edges.**\n",
         "\n```mermaid\ngraph LR"]
    for n in ckm["nodes"]:
        L.append(f'  {_nid(n["id"])}["{n["label"]}<br/><i>{n["type"]}</i>"]')
    for e in ckm["edges"]:
        L.append(f"  {_nid(e['from'])} -->|{e['predicate']}| {_nid(e['to'])}")
    for family in ("descriptive", "operational"):
        ids = [_nid(n["id"]) for n in ckm["nodes"] if n["family"] == family]
        if ids:
            L.append(f"  class {','.join(ids)} {family};")
    L += ["  classDef descriptive fill:#e8f0fe,stroke:#4285f4;",
          "  classDef operational fill:#fce8e6,stroke:#ea4335;", "```\n"]
    return "\n".join(L)
