#!/usr/bin/env python3
"""Generate three graph views of the Engineering OS metamodel.

Reads:  model/metamodel/entities/*.md   (relationship tables)
        model/metamodel/ontology/*.ttl  (class hierarchy, object properties)
Writes: model/metamodel/views/*.md      (Mermaid graphs + structural metrics)

These are DERIVED artifacts (ADR-0012). Do not edit the output by hand; edit
the sources and regenerate. This is the first mechanically generated projection
in the repository (ISSUE-0037).

Semantic Layer: None — cross-cutting infrastructure (ADR-0039).
"""
import re
import sys
import pathlib
import itertools
import collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTITIES = ROOT / "model/metamodel/entities"
TTL = ROOT / "model/metamodel/ontology/engineering-os-metamodel.ttl"
OUT = ROOT / "model/metamodel/views"

BANNER = (
    "> **Generated by `tools/generate-metamodel-views.py`. Do not edit.**\n"
    "> A derived artifact (`ADR-0012`). Edit the sources and regenerate.\n"
)


# --------------------------------------------------------------------------
# Sources
# --------------------------------------------------------------------------
def read_entities():
    """entity name -> {'family':..., 'rels':[(relation, target, cardinality)]}"""
    out = {}
    for path in sorted(ENTITIES.glob("*.md")):
        text = path.read_text()
        title = re.search(r"^title:\s*(\S+)", text, re.M)
        family = re.search(r"^entity-family:\s*(\S+)", text, re.M)
        if not title:
            continue
        rels = []
        section = re.search(r"^## relationships\n(.*?)(?=^## )", text, re.M | re.S)
        if section:
            for row in re.findall(r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]*?)\s*\|",
                                  section.group(1), re.M):
                rel, target, card = (c.strip() for c in row)
                if rel in ("Relationship", "---") or set(rel) <= {"-"}:
                    continue
                rels.append((rel, target, card))
        out[title.group(1)] = {
            "family": family.group(1) if family else "unassigned",
            "rels": rels,
            "file": path.name,
        }
    return out


def read_ttl():
    """Returns (subclass_edges, property_edges, kinds). Parsed, not pattern-matched."""
    import rdflib
    from rdflib.namespace import OWL, RDF, RDFS

    g = rdflib.Graph()
    g.parse(TTL, format="turtle")
    EOS = rdflib.Namespace("https://example.org/engineering-os/metamodel#")

    def local(node):
        return str(node)[len(str(EOS)):] if str(node).startswith(str(EOS)) else None

    kinds = {}
    for c in g.subjects(RDF.type, OWL.Class):
        if local(c):
            kinds[local(c)] = "class"
    for t in (OWL.ObjectProperty, OWL.DatatypeProperty):
        for p in g.subjects(RDF.type, t):
            if local(p):
                kinds[local(p)] = "property"

    subclass = [(local(c), local(s))
                for c, s in g.subject_objects(RDFS.subClassOf)
                if local(c) and local(s)]

    def domains_of(p):
        """Named domain, or the members of an owl:unionOf domain."""
        out = []
        for d in g.objects(p, RDFS.domain):
            if local(d):
                out.append(local(d))
            else:
                for u in g.objects(d, OWL.unionOf):
                    out += [local(m) for m in rdflib.collection.Collection(g, u) if local(m)]
        return out

    props = []
    for p in g.subjects(RDF.type, OWL.ObjectProperty):
        if not local(p):
            continue
        ranges = [local(r) for r in g.objects(p, RDFS.range) if local(r)]
        for d in domains_of(p):
            for r in ranges:
                props.append((d, local(p), r))

    return subclass, props, kinds


# --------------------------------------------------------------------------
# Structural metrics — what the graphs are inspected FOR
# --------------------------------------------------------------------------
def metrics(nodes, edges):
    """edges: list of (src, label, dst)"""
    neigh = collections.defaultdict(set)
    outd, ind = collections.Counter(), collections.Counter()
    for s, _, d in edges:
        neigh[s].add(d)
        neigh[d].add(s)
        outd[s] += 1
        ind[d] += 1

    degree = {n: len(neigh[n]) for n in nodes}
    isolated = sorted(n for n in nodes if degree.get(n, 0) == 0)
    pendant = sorted(n for n in nodes if degree.get(n, 0) == 1)
    hubs = sorted(((d, n) for n, d in degree.items() if d >= 5), reverse=True)

    similar = []
    for a, b in itertools.combinations(sorted(nodes), 2):
        na, nb = neigh[a] - {b}, neigh[b] - {a}
        if not na or not nb:
            continue
        j = len(na & nb) / len(na | nb)
        if j >= 0.6:
            similar.append((round(j, 2), a, b, sorted(na & nb)))
    similar.sort(reverse=True)

    chains = sorted(n for n in nodes if ind[n] == 1 and outd[n] == 1 and degree.get(n, 0) <= 2)

    motifs = collections.Counter(label for _, label, _ in edges)
    repeated = sorted(((c, m) for m, c in motifs.items() if c >= 3), reverse=True)

    return dict(isolated=isolated, pendant=pendant, hubs=hubs,
                similar=similar, chains=chains, repeated=repeated, degree=degree)


def render_metrics(m, nodes):
    L = []
    L.append("## Structural metrics\n")
    L.append(f"**{len(nodes)} nodes.** Computed from the graph, not read from the specifications.\n")

    L.append("### Isolated and near-isolated\n")
    if m["isolated"]:
        L.append("**Isolated (degree 0):** " + ", ".join(f"`{n}`" for n in m["isolated"]) + "\n")
    else:
        L.append("No isolated nodes.\n")
    if m["pendant"]:
        L.append("**Pendant (degree 1):** " + ", ".join(f"`{n}`" for n in m["pendant"]) + "\n")

    L.append("### Hubs (degree ≥ 5)\n")
    L.append("| Node | Degree |\n|---|---|")
    for d, n in m["hubs"][:12]:
        L.append(f"| `{n}` | {d} |")
    L.append("")

    L.append("### Near-identical neighbourhoods (Jaccard ≥ 0.6)\n")
    if m["similar"]:
        L.append("| Similarity | A | B | Shared neighbours |\n|---|---|---|---|")
        for j, a, b, shared in m["similar"][:15]:
            L.append(f"| {j} | `{a}` | `{b}` | {', '.join(f'`{s}`' for s in shared)} |")
    else:
        L.append("None above threshold.")
    L.append("")

    L.append("### Chains (in-degree 1, out-degree 1)\n")
    L.append(", ".join(f"`{n}`" for n in m["chains"]) if m["chains"] else "None.")
    L.append("")

    L.append("### Repeated motifs (relation used ≥ 3 times)\n")
    if m["repeated"]:
        L.append("| Count | Relation |\n|---|---|")
        for c, r in m["repeated"][:15]:
            L.append(f"| {c} | `{r}` |")
    else:
        L.append("None.")
    L.append("")
    return "\n".join(L)


def mermaid(edges, node_classes=None, direction="LR"):
    L = [f"```mermaid\ngraph {direction}"]
    seen = set()
    for s, label, d in edges:
        sid, did = s.replace("-", "_"), d.replace("-", "_")
        for n, i in ((s, sid), (d, did)):
            if i not in seen:
                L.append(f"  {i}[{n}]")
                seen.add(i)
        L.append(f"  {sid} -->|{label}| {did}")
    for cls, members in (node_classes or {}).items():
        ids = [m.replace("-", "_") for m in members if m.replace("-", "_") in seen]
        if ids:
            L.append(f"  class {','.join(ids)} {cls};")
    if node_classes:
        L.append("  classDef descriptive fill:#e8f0fe,stroke:#4285f4;")
        L.append("  classDef operational fill:#fce8e6,stroke:#ea4335;")
    L.append("```")
    return "\n".join(L)


# --------------------------------------------------------------------------
def main():
    OUT.mkdir(parents=True, exist_ok=True)
    ents = read_entities()
    subclass, props, kinds = read_ttl()
    names = set(ents)

    # ---- View 1: Markdown entity graph -----------------------------------
    edges = []
    for name, info in ents.items():
        for rel, target, _ in info["rels"]:
            for cand in re.split(r",| or ", target):
                cand = cand.strip().strip("`*")
                if cand in names and cand != name:
                    edges.append((name, rel, cand))
    fams = collections.defaultdict(list)
    for n, i in ents.items():
        fams[i["family"]].append(n)

    (OUT / "01-entity-graph.md").write_text(
        "# View 1 — Markdown entity graph\n\n" + BANNER +
        "\nEdges are the `relationships` tables of every entity specification, "
        "restricted to targets that are themselves specified entities.\n\n"
        f"**{len(names)} entities, {len(edges)} internal edges.**\n\n"
        + mermaid(edges, {"descriptive": fams["descriptive"], "operational": fams["operational"]})
        + "\n\n" + render_metrics(metrics(names, edges), names))

    # ---- View 2: OWL class hierarchy -------------------------------------
    classes = {n for n, k in kinds.items() if k == "class"}
    sub_edges = [(c, "is-a", p) for c, p in subclass]
    (OUT / "02-class-hierarchy.md").write_text(
        "# View 2 — OWL class hierarchy\n\n" + BANNER +
        "\n`rdfs:subClassOf` between named classes. Restrictions are blank nodes "
        "and do not appear.\n\n"
        f"**{len(classes)} classes, {len(sub_edges)} subclass edges.**\n\n"
        + mermaid(sub_edges, direction="BT") + "\n\n"
        + render_metrics(metrics(classes, sub_edges), classes))

    # ---- View 3: Relationship dependency graph ---------------------------
    prop_edges = [(d, p, r) for d, p, r in props]
    prop_nodes = {n for e in prop_edges for n in (e[0], e[2])}
    (OUT / "03-relationship-graph.md").write_text(
        "# View 3 — Relationship dependency graph\n\n" + BANNER +
        "\nEvery `owl:ObjectProperty` with a declared domain and a named range. "
        "Properties whose range was deliberately omitted do not appear — that "
        "omission is itself a finding (`FINDINGS.md` #8).\n\n"
        f"**{len(prop_nodes)} classes connected by {len(prop_edges)} properties.**\n\n"
        + mermaid(prop_edges) + "\n\n"
        + render_metrics(metrics(prop_nodes, prop_edges), prop_nodes))

    print(f"entity graph      : {len(names)} nodes, {len(edges)} edges")
    print(f"class hierarchy   : {len(classes)} nodes, {len(sub_edges)} edges")
    print(f"relationship graph: {len(prop_nodes)} nodes, {len(prop_edges)} edges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
